#!/bin/python

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(raw_input())

for number in range(1, 11):
    print ("{} x {} = {}" .format(n, number, n*number))
